### ISSUE TITLE
Verification compare should be constant time

### ISSUE THREAD

**Issue by ecki** [henrycg/balloon#8]
https://github.com/henrycg/balloon/blob/0ae35a8879a97f4c7c44ee7fe77ea6522c607ef7/libballoon/api.c#L79

i am not sure if memcmp is Safe of vectorized and small, but using `CRYPTO_memcmp` would be more common usage (not sure how good ,)

**Comment by henrycg** [comment]
Fixed in [35d7da7](https://github.com/henrycg/balloon/commit/35d7da79f42b4f9078ba6f39e1e0a5a37bafa4c1). Thanks!
